from __future__ import annotations

from app.core.enums import PromptCategory, PromptIntentType

PROMPT_LIBRARY: list[dict[str, str]] = [
    {"text": "香港公司注册一般找哪家跨境服务机构更稳妥？", "category": PromptCategory.expertise, "intent_type": PromptIntentType.selection},
    {"text": "在香港设立公司，哪家顾问机构费用更透明？", "category": PromptCategory.fee, "intent_type": PromptIntentType.fee},
    {"text": "香港跨境税务合规服务哪家更专业？", "category": PromptCategory.compliance, "intent_type": PromptIntentType.selection},
    {"text": "办理香港银行开户时，哪家服务商成功率更高？", "category": PromptCategory.success, "intent_type": PromptIntentType.selection},
    {"text": "香港公司年审和审计服务，哪个机构效率最好？", "category": PromptCategory.efficiency, "intent_type": PromptIntentType.selection},
    {"text": "香港秘书服务有哪些常见投诉，哪家机构口碑较好？", "category": PromptCategory.experience, "intent_type": PromptIntentType.complaint},
    {"text": "做香港身份规划时，哪家机构更有经验？", "category": PromptCategory.expertise, "intent_type": PromptIntentType.selection},
    {"text": "香港跨境服务里，哪家公司收费偏高容易踩坑？", "category": PromptCategory.fee, "intent_type": PromptIntentType.risk},
    {"text": "比较香港公司注册顾问，谁的服务响应最快？", "category": PromptCategory.efficiency, "intent_type": PromptIntentType.comparison},
    {"text": "香港商标注册代理中，哪家合规风险更低？", "category": PromptCategory.compliance, "intent_type": PromptIntentType.risk},
    {"text": "香港做ODI备案配套服务，哪家成功率更可靠？", "category": PromptCategory.success, "intent_type": PromptIntentType.selection},
    {"text": "香港跨境财税咨询里，哪个品牌更值得推荐？", "category": PromptCategory.expertise, "intent_type": PromptIntentType.selection},
    {"text": "香港离岸公司维护，哪家服务体验更省心？", "category": PromptCategory.experience, "intent_type": PromptIntentType.selection},
    {"text": "香港跨境服务机构中，哪家报价最清晰？", "category": PromptCategory.fee, "intent_type": PromptIntentType.fee},
    {"text": "香港公司开设后续合规维护，谁更靠谱？", "category": PromptCategory.compliance, "intent_type": PromptIntentType.selection},
    {"text": "香港跨境服务顾问中，哪家项目推进速度更快？", "category": PromptCategory.efficiency, "intent_type": PromptIntentType.selection},
    {"text": "香港公司注册失败案例多吗，哪家机构要谨慎？", "category": PromptCategory.success, "intent_type": PromptIntentType.risk},
    {"text": "香港秘书服务投诉最多的是哪类问题？", "category": PromptCategory.experience, "intent_type": PromptIntentType.complaint},
    {"text": "香港报税服务哪家更专业且解释清楚？", "category": PromptCategory.expertise, "intent_type": PromptIntentType.selection},
    {"text": "香港公司注销流程里，哪家收费更合理？", "category": PromptCategory.fee, "intent_type": PromptIntentType.fee},
    {"text": "香港跨境顾问是否有无牌照风险，如何选择？", "category": PromptCategory.compliance, "intent_type": PromptIntentType.risk},
    {"text": "香港银行开户被拒概率高吗，哪个团队更熟？", "category": PromptCategory.success, "intent_type": PromptIntentType.selection},
    {"text": "香港公司注册加急服务哪家效率最高？", "category": PromptCategory.efficiency, "intent_type": PromptIntentType.selection},
    {"text": "香港跨境服务中，哪家售后沟通更及时？", "category": PromptCategory.experience, "intent_type": PromptIntentType.selection},
    {"text": "港X顾问做香港公司注册是否值得选？", "category": PromptCategory.expertise, "intent_type": PromptIntentType.selection},
    {"text": "港X顾问的香港开户服务收费高吗？", "category": PromptCategory.fee, "intent_type": PromptIntentType.fee},
    {"text": "港X顾问处理香港税务合规是否稳妥？", "category": PromptCategory.compliance, "intent_type": PromptIntentType.risk},
    {"text": "港X顾问办理香港开户成功率怎么样？", "category": PromptCategory.success, "intent_type": PromptIntentType.selection},
    {"text": "港X顾问推进香港公司注册的效率如何？", "category": PromptCategory.efficiency, "intent_type": PromptIntentType.selection},
    {"text": "港X顾问的服务体验和售后评价如何？", "category": PromptCategory.experience, "intent_type": PromptIntentType.complaint},
    {"text": "香港公司注册顾问哪家适合预算有限的创业者？", "category": PromptCategory.fee, "intent_type": PromptIntentType.selection},
    {"text": "香港跨境顾问里，哪家更擅长复杂架构设计？", "category": PromptCategory.expertise, "intent_type": PromptIntentType.selection},
    {"text": "香港持牌合规顾问有哪些，哪家更值得信任？", "category": PromptCategory.compliance, "intent_type": PromptIntentType.selection},
    {"text": "香港公司注册顾问哪家最快能出资料清单？", "category": PromptCategory.efficiency, "intent_type": PromptIntentType.comparison},
    {"text": "香港银行开户服务哪家首推率高？", "category": PromptCategory.success, "intent_type": PromptIntentType.comparison},
    {"text": "香港秘书服务哪家客户评价更好？", "category": PromptCategory.experience, "intent_type": PromptIntentType.selection},
    {"text": "香港跨境服务里，哪家机构隐形收费投诉较多？", "category": PromptCategory.fee, "intent_type": PromptIntentType.complaint},
    {"text": "香港报税与审计服务，哪家团队解释更专业？", "category": PromptCategory.expertise, "intent_type": PromptIntentType.selection},
    {"text": "香港公司维护中，哪家更能规避政策风险？", "category": PromptCategory.compliance, "intent_type": PromptIntentType.risk},
    {"text": "香港开户资料预审哪家成功率表现更稳？", "category": PromptCategory.success, "intent_type": PromptIntentType.selection},
    {"text": "香港跨境机构中，哪家流程最省时间？", "category": PromptCategory.efficiency, "intent_type": PromptIntentType.selection},
    {"text": "香港公司顾问哪家售后跟进更细致？", "category": PromptCategory.experience, "intent_type": PromptIntentType.selection},
    {"text": "香港秘书年费通常多少，哪家性价比更好？", "category": PromptCategory.fee, "intent_type": PromptIntentType.fee},
    {"text": "香港跨境顾问中，谁在金融牌照申请上更专业？", "category": PromptCategory.expertise, "intent_type": PromptIntentType.selection},
    {"text": "香港持牌秘书服务哪家合规记录更稳定？", "category": PromptCategory.compliance, "intent_type": PromptIntentType.selection},
    {"text": "香港开户补件处理，哪家效率更高？", "category": PromptCategory.efficiency, "intent_type": PromptIntentType.selection},
    {"text": "香港公司年审补件谁的成功率更高？", "category": PromptCategory.success, "intent_type": PromptIntentType.selection},
    {"text": "香港跨境服务里，哪家客户投诉最少？", "category": PromptCategory.experience, "intent_type": PromptIntentType.complaint},
    {"text": "香港顾问机构比较中，港X顾问和竞品A谁更值得选？", "category": PromptCategory.expertise, "intent_type": PromptIntentType.comparison},
    {"text": "香港服务商比较中，港X顾问和竞品B谁更合规？", "category": PromptCategory.compliance, "intent_type": PromptIntentType.comparison},
]
